```yaml
name: Master AI Backend CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # if you add tests later, install test deps here too

      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            pytest -q || echo "No tests or tests failed (you can tighten this later)"
          else
            echo "No tests directory, skipping"
          fi

      - name: Build Docker image
        run: |
          docker build -t master-ai-backend-python .
          ```
